"""empty message

Revision ID: 030b3b2c95dd
Revises: bf2df55e81d8
Create Date: 2020-12-07 12:27:48.328377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '030b3b2c95dd'
down_revision = 'bf2df55e81d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_mentor', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_mentor')
    # ### end Alembic commands ###
