"""empty message

Revision ID: 10d6e99ea1ba
Revises: b59e276f9590
Create Date: 2021-02-12 11:25:44.116150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10d6e99ea1ba'
down_revision = 'b59e276f9590'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'availability')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('availability', sa.VARCHAR(length=19), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
