"""empty message

Revision ID: 3a6cd7a983d4
Revises: 10d6e99ea1ba
Create Date: 2021-02-12 11:26:31.341521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a6cd7a983d4'
down_revision = '10d6e99ea1ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('availability', sa.Enum('available', 'partial', 'booked', 'not_interested', name='useravailability', native_enum=False), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'availability')
    # ### end Alembic commands ###
