"""empty message

Revision ID: 3c825fac5bf3
Revises: 7658bf817c7a
Create Date: 2020-10-01 13:30:13.303049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c825fac5bf3'
down_revision = '7658bf817c7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users',
        sa.Column(
            'type',
            sa.Enum('user', 'admin', 'super_admin', name='usertype', native_enum=False),
            nullable=True,
        ),
    )
    op.execute("UPDATE users SET type = 'user'")
    op.alter_column('users', 'type', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'type')
    # ### end Alembic commands ###
