"""empty message

Revision ID: 44b3f85dee45
Revises: 5e518686855c
Create Date: 2021-01-29 10:39:13.544579

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '44b3f85dee45'
down_revision = '5e518686855c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('descriptions', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'descriptions')
    # ### end Alembic commands ###
