"""empty message

Revision ID: 827828c372f0
Revises: 3c825fac5bf3
Create Date: 2020-10-12 12:21:04.019472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '827828c372f0'
down_revision = '3c825fac5bf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('country', sa.String(), nullable=True))
    op.add_column('users', sa.Column('department', sa.String(), nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('users', sa.Column('position', sa.String(), nullable=True))
    op.add_column('users', sa.Column('street', sa.String(), nullable=True))
    op.add_column('users', sa.Column('town', sa.String(), nullable=True))
    op.add_column('users', sa.Column('zip_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'zip_code')
    op.drop_column('users', 'town')
    op.drop_column('users', 'street')
    op.drop_column('users', 'position')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'department')
    op.drop_column('users', 'country')
    # ### end Alembic commands ###
