"""empty message

Revision ID: 8294d1ad672d
Revises: d75e2f635756
Create Date: 2020-11-19 12:07:50.618881

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8294d1ad672d'
down_revision = 'd75e2f635756'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'event_logs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('stream_reference', sa.String(length=36), nullable=False),
        sa.Column('created', sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_event_logs_stream_reference'), 'event_logs', ['stream_reference'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_logs_stream_reference'), table_name='event_logs')
    op.drop_table('event_logs')
    # ### end Alembic commands ###
