"""empty message

Revision ID: bf2df55e81d8
Revises: 8294d1ad672d
Create Date: 2020-12-04 15:35:32.080669

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bf2df55e81d8'
down_revision = '8294d1ad672d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users', sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'skills')
    # ### end Alembic commands ###
