"""empty message

Revision ID: d607443d4240
Revises: fe190fe44af6
Create Date: 2021-02-07 12:32:25.739159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd607443d4240'
down_revision = 'fe190fe44af6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qa_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('created', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['qa_posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qa_posts_author_id'), 'qa_posts', ['author_id'], unique=False)
    op.create_index(op.f('ix_qa_posts_parent_id'), 'qa_posts', ['parent_id'], unique=False)
    op.create_index(op.f('ix_qa_posts_reference'), 'qa_posts', ['reference'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_qa_posts_reference'), table_name='qa_posts')
    op.drop_index(op.f('ix_qa_posts_parent_id'), table_name='qa_posts')
    op.drop_index(op.f('ix_qa_posts_author_id'), table_name='qa_posts')
    op.drop_table('qa_posts')
    # ### end Alembic commands ###
