"""empty message

Revision ID: d75e2f635756
Revises: dbb1f6ce678b
Create Date: 2020-10-30 13:00:55.367452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd75e2f635756'
down_revision = 'dbb1f6ce678b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'invitations',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('reference', sa.String(length=36), nullable=False),
        sa.Column('email_address', sa.String(), nullable=True),
        sa.Column('redeemed', sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column('created', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
        sa.Column('creator_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['creator_id'],
            ['users.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email_address'),
    )
    op.create_index(op.f('ix_invitations_creator_id'), 'invitations', ['creator_id'], unique=False)
    op.create_index(op.f('ix_invitations_reference'), 'invitations', ['reference'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invitations_reference'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_creator_id'), table_name='invitations')
    op.drop_table('invitations')
    # ### end Alembic commands ###
