"""empty message

Revision ID: fe190fe44af6
Revises: 44b3f85dee45
Create Date: 2021-02-01 11:46:46.484713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe190fe44af6'
down_revision = '44b3f85dee45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('availability', sa.Enum('AVAILABLE', 'PARTIALLY_AVAILABLE', 'BUSY', 'NOT_INTERESTED', name='useravailability', native_enum=False), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'availability')
    # ### end Alembic commands ###
