"""empty message

Revision ID: decacc61c183
Revises: ed2029d7ce92
Create Date: 2021-03-19 14:19:16.976604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'decacc61c183'
down_revision = 'ed2029d7ce92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('deleted', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('qa_posts', sa.Column('deleted', sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('qa_posts', 'deleted')
    op.drop_column('posts', 'deleted')
    # ### end Alembic commands ###
