"""empty message

Revision ID: ed2029d7ce92
Revises: f392e7b8445a
Create Date: 2021-03-16 18:09:15.586244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed2029d7ce92'
down_revision = 'f392e7b8445a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('deleted', sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'deleted')
    # ### end Alembic commands ###
